# GitHub Nodejs CI
name: nodejs

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run test
        env:
          CI: ''

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: false
